---
name: CI

on:
  push:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: github/super-linter@v3
    env:
      VALIDATE_ALL_CODEBASE: false
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.github-action }}

    sast:
      runs-on: ubuntu-latest
      needs:
        - lint
      steps:
        - uses: github/checkout@v2

        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Run static code analysis
          run: |
            pip3 install -r requirements.txt
            bandit app.py

    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-verison: '3.x
        - name: Install dependencies
          run: |
            pip3 install -r requirements.txt
            python -m pytest
